export type {
    DIDResolver,
    IMessage,
    Message as DIDCommMessage,
    PackEncryptedMetadata,
    PackEncryptedOptions,
    PackSignedMetadata,
    ParsedForward as DIDCommParsedForward,
    SecretsResolver,
    UnpackMetadata,
    UnpackOptions,
    DIDDoc,
    Secret,
    AttachmentData,
    Base64AttachmentData,
    DIDCommMessagingService,
    Service,
    FromPrior as DIDCommFromPrior,
    IFromPrior,
    JsonAttachmentData,
    LinksAttachmentData,
    IParsedForward,
    SecretMaterial,
    MessagingServiceMetadata,
    SecretType,
    ServiceKind,
    VerificationMaterial,
    SecretMaterialFormat,
    VerificationMaterialFormat,
    VerificationMethod,
    VerificationMethodType,
    Attachment
} from 'didcomm'
