export type {
    DIDResolver,
    IMessage,
    Message as DIDCommMessage,
    PackEncryptedMetadata,
    PackEncryptedOptions,
    PackSignedMetadata,
    ParsedForward,
    SecretsResolver,
    UnpackMetadata,
    UnpackOptions,
    DIDDoc,
    Secret,
    AttachmentData,
    Base64AttachmentData,
    DIDCommMessagingService,
    Service,
    FromPrior,
    IFromPrior,
    JsonAttachmentData,
    LinksAttachmentData,
    IParsedForward,
    SecretMaterial,
    MessagingServiceMetadata,
    SecretType,
    ServiceKind,
    VerificationMaterial,
    SecretMaterialFormat,
    VerificationMaterialFormat,
    VerificationMethod,
    VerificationMethodType,
    Attachment
} from 'didcomm'
